FIRST_RECONNECT_DELAY = 1
RECONNECT_RATE = 2
MAX_RECONNECT_COUNT = 12
MAX_RECONNECT_DELAY = 60

# Topics
TEMPERATURE_TOPIC = "temperature"
HUMIDITY_TOPIC = "humidity"
PRESSURE_TOPIC = "pressure"
LIGHT_TOPIC = "light"
WATER_LEVEL_TOPIC = "water_level"
WATER_PH_TOPIC = "water_ph"
SOIL_PH_TOPIC = "ph"